version: '3.8'

services:
  # Сервис базы данных PostgreSQL с расширением PostGIS
  db:
    # Используем официальный образ с PostGIS
    image: postgis/postgis:15-3.4
    # Имя контейнера для удобства
    container_name: farmnavigator_db
    # Переменные окружения для настройки БД
    environment:
      POSTGRES_USER: user_farm
      POSTGRES_PASSWORD: password_farm
      POSTGRES_DB: db_farm
    # Пробрасываем порт 5432 из контейнера на ваш компьютер
    ports:
      - "5432:5432"
    # Сохраняем данные БД на вашем диске, чтобы они не терялись при перезапуске контейнера
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Перезапускать контейнер автоматически в случае сбоя
    restart: always

volumes:
  # Определяем "том" для хранения данных
  postgres_data: