version: '3.8'

services:
  db:
    # 1. Берём готовый образ PostgreSQL с поддержкой карт (PostGIS)
    image: postgis/postgis:15-3.4
    container_name: farmnavigator_db

    # 2. Говорим контейнеру, чтобы он взял логин и пароль из файла .env
    env_file:
      - ./.env

    ports:
      - "5432:5432"

    volumes:
      # Эта строчка нужна, чтобы данные не терялись после перезапуска
      - postgres_data:/var/lib/postgresql/data

      # 3. САМОЕ ГЛАВНОЕ:
      # "Кладём" нашу папку db_init с SQL-скриптом внутрь контейнера.
      # Docker сам найдёт там init.sql и выполнит его при первом запуске.
      - ./db_init:/docker-entrypoint-initdb.d

    restart: always

volumes:
  postgres_data: